# -*- coding: utf-8 -*-
"""Week_1_Hotel_Booking_Data_Cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxX4HdUktx7CNjbZHsNNRFR8k1kCR7Ou
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("hotel_bookings.csv")
df.head()
df.shape
df.columns
df.dtypes
df.info()
df.describe()
missing_values = df.isnull().sum()

missing_values[missing_values > 0]
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage[missing_percentage > 0].sort_values(ascending=False)
df.duplicated().sum()
df[df.duplicated()]
df = df.drop_duplicates()
df = df.drop_duplicates()
df.isnull().sum().sort_values(ascending=False)
missing_values = df.isnull().sum()

missing_values[missing_values > 0]
df["Country"] = df["Country"].fillna("Unknown")
df["Country"].isnull().sum()
missing_values = df.isnull().sum()

missing_values[missing_values > 0]
df.duplicated().sum()